before_all do
  cocoapods
end

lane :up_tf do
  increment_build_number
  sigh :adhoc
  build_ipa
  upload_testflight
end

def upload_testflight
  system("deliver testflight ../releases/partyUp.ipa -u lioyufrj@gmail.com -a 917468380")
end


def build_ipa
  ipa({
    workspace: "partyUp.xcworkspace",
    configuration: "Release",
    scheme: "partyUp",
    destination: "./releases"
  })
end


after_all do |lane|
  # This block is called, only if the executed lane was successful
  # slack({
  #   message: "Successfully deployed new App Update for [App](http://link.com).",
  #   success: true,
  #   channel: 'development'
  # })
end


error do |lane, exception|
  # Something bad happened
end
