platform :ios, '7.1'
target :partyUp do
pod 'SVPullToRefresh'
pod 'SDWebImage', '~>3.6'
pod 'UIResponder+KeyboardCache'
pod 'Facebook-iOS-SDK'
pod 'Parse'
pod 'ParseFacebookUtils'
pod 'GoogleAnalytics-iOS-SDK'
pod 'DBEnvironmentConfiguration'
pod "FDKeychain", "~> 1.0.0"
pod 'currencyParser', :git => 'https://github.com/thiagolioy/currencyParser.git'

end
